# Generated by Django 5.0.3 on 2024-03-23 10:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1900), django.core.validators.MinValueValidator(2100)])),
                ('length', models.TimeField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MinValueValidator(10)])),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.director')),
            ],
        ),
    ]
